---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db-deployment
  namespace: abc2018sg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sql2017
        image: microsoft/mssql-server-linux
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "3Gi"
        ports:
        - name: dbport
          containerPort: 1433
        # livenessProbe:
        #   tcpSocket:
        #     port: dbport
        #   initialDelaySeconds: 20
        #   periodSeconds: 15
        # readinessProbe:
        #     tcpSocket:
        #       port: dbport
        #     initialDelaySeconds: 20
        #     periodSeconds: 15
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: January2018
          # valueFrom:
          #   secretKeyRef:
          #     name: mssql
          #     key: SA_PASSWORD
        - name: MSSQL_PID
          value: Developer
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: techtalksdb-data